@url = http://localhost:3333/v1

POST {{url}}/auth
Content-Type: application/json

{
 "email": "serra.henrique3@gmail.com", 
 "password": "batatinha123"
}

###

GET {{url}}/auth/check
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDcxODY1OTcsImV4cCI6MTc0NzQ0NTc5Nywic3ViIjoiMSJ9.uqtje-RcQWBC-MNSU_vMBMrW2nnMvQTJVmVHflqBwkE"
}
###

POST {{url}}/forgot-password
Content-Type: application/json

{
 "email": "serra.henrique3@gmail.com"
}
###

PUT {{url}}/students/1
Content-Type: application/json

{
 "fullname": "henrique", 
 "birthdate": "11/10/1999",
 "cpf": "347.728.870-08"
}

###

DELETE  {{url}}/students/1
Content-Type: application/json

