@url = http://localhost:3333/v1
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXN0ZSI6IjEiLCJpYXQiOjE3NDc4NTUxMzYsImV4cCI6MTc0Nzg1ODczNiwic3ViIjoiMSJ9.dDpnIYgIAMoabxcjFF3JLqIOecONLYzbPO9BNaMFYuc

POST {{url}}/students
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
 "fullname": "henrique", 
 "birthdate": "11/10/1999", 
 "cpf": "898.825.970-09"
}

###

GET {{url}}/students
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

GET {{url}}/students/1
Authorization: Bearer {{authToken}}
Content-Type: application/json


###

PUT {{url}}/students/1
Content-Type: application/json

{
 "fullname": "henrique", 
 "birthdate": "11/10/1999",
 "cpf": "347.728.870-08"
}

###

DELETE  {{url}}/students/1
Content-Type: application/json

