@url = http://localhost:3333/v1

POST {{url}}/users
Content-Type: application/json

{
   "fullname": "Henrique Admin",
    "role": "admin",
    "email": "serra.henrique1@gmail.com",
    "password": "batatinha123"
}

###

GET {{url}}/users
Content-Type: application/json

###

GET {{url}}/users/1
Content-Type: application/json


###

PUT {{url}}/users/1
Content-Type: application/json

{
    "fullname": "Henrique User",
    "role": "admin",
    "password": "12345678"
}

###

DELETE  {{url}}/users/1
Content-Type: application/json

